// Generated by scripts/sync_wiki.py; do not edit.
import { defineConfig } from "vitepress";

const activeItems = [

];

const archivedItems = [
  { text: "configure-qwen-model-providers", link: "/changes/archive/2026-09-09-configure-qwen-model-providers/" },
  { text: "setup-sqlite-repository-foundation", link: "/changes/archive/2026-09-08-setup-sqlite-repository-foundation/" },
  { text: "establish-project-foundation", link: "/changes/archive/2026-09-08-establish-project-foundation/" },
  { text: "enforce-tenant-isolation", link: "/changes/archive/2026-09-08-enforce-tenant-isolation/" },
  { text: "define-api-and-sse-contracts", link: "/changes/archive/2026-09-08-define-api-and-sse-contracts/" },
  { text: "add-user-authentication", link: "/changes/archive/2026-09-08-add-user-authentication/" },
  { text: "repair-wiki-sync-workflow", link: "/changes/archive/2026-08-28-repair-wiki-sync-workflow/" },
  { text: "integrate-matt-skills-with-openspec", link: "/changes/archive/2026-08-26-integrate-matt-skills-with-openspec/" },
  { text: "improve-claude-md-guidance", link: "/changes/archive/2026-08-26-improve-claude-md-guidance/" },
];

export default defineConfig({
  lang: "zh-CN",
  title: "On-call Pilot WIKI",
  description: "On-call Pilot 项目文档与 OpenSpec 变更记录",
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: "首页", link: "/" },
      { text: "变更 WIKI", link: "/changes/" }
    ],
    sidebar: {
      "/changes/": [
        { text: "总览", items: [{ text: "变更索引", link: "/changes/" }] },
        { text: "进行中", collapsed: false, items: activeItems },
        { text: "已归档", collapsed: true, items: archivedItems }
      ]
    },
    search: { provider: "local" },
    outline: { level: [2, 3], label: "本页目录" },
    docFooter: { prev: "上一页", next: "下一页" },
    sidebarMenuLabel: "目录",
    returnToTopLabel: "返回顶部"
  }
});
