#!/usr/bin/env python3
"""将 OpenSpec Change 确定性投影为 VitePress WIKI 页面。"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

Mode = Literal["active", "archive", "all"]
Operation = Literal["ADDED", "MODIFIED", "REMOVED"]

INCLUDE_RE = re.compile(r"<!--@include:\s*(.+?)-->")
REQUIREMENT_RE = re.compile(r"^### Requirement:\s*(.+?)\s*$", re.MULTILINE)
OPERATION_RE = re.compile(
    r"^## (ADDED|MODIFIED|REMOVED|RENAMED) Requirements\s*$", re.MULTILINE
)
INDEX_LINK_RE = re.compile(r"^- \[[^]]+\]\((/changes/(?:active|archive)/[^)]+/)\)$")
CONFIG_LINK_RE = re.compile(
    r'^\s*\{ text: .+?, link: "(/changes/(?:active|archive)/.+?/)" \},?$',
    re.MULTILINE,
)
GENERATED_MARKER = "<!-- Generated by scripts/sync_wiki.py; do not edit. -->"
ARTIFACT_SECTIONS = (
    ("提案", "proposal.md"),
    ("设计", "design.md"),
    ("任务", "tasks.md"),
)


class WikiSyncError(RuntimeError):
    """表示同步无法安全完成。"""


@dataclass(frozen=True, slots=True)
class WikiRepository:
    """集中同步器使用的仓库路径。"""

    root: Path

    @property
    def changes(self) -> Path:
        return self.root / "openspec" / "changes"

    @property
    def main_specs(self) -> Path:
        return self.root / "openspec" / "specs"

    @property
    def docs(self) -> Path:
        return self.root / "docs"

    @property
    def active_docs(self) -> Path:
        return self.docs / "changes" / "active"

    @property
    def archive_docs(self) -> Path:
        return self.docs / "changes" / "archive"

    @property
    def index(self) -> Path:
        return self.docs / "changes" / "index.md"

    @property
    def config(self) -> Path:
        return self.docs / ".vitepress" / "config.mts"


@dataclass(frozen=True, slots=True)
class ChangePage:
    directory_name: str
    title: str
    status: Literal["active", "archived"]
    created_date: str
    archived_date: str | None
    source_dir: Path
    output_dir: Path

    @property
    def link(self) -> str:
        group = "active" if self.status == "active" else "archive"
        return f"/changes/{group}/{self.directory_name}/"


@dataclass(frozen=True, slots=True)
class SpecOperation:
    archive_name: str
    capability: str
    operation: Operation
    requirement: str
    body: str | None


@dataclass(frozen=True, slots=True)
class SyncResult:
    active_count: int
    archive_count: int
    include_count: int
    selected: str | None
    warnings: tuple[str, ...]


def sync_wiki(
    repo_root: Path,
    mode: str,
    name: str | None = None,
    *,
    allow_unsynced: bool = False,
) -> SyncResult:
    """同步整个仓库的 WIKI，并验证选中的 Change 存在。"""

    validated_mode = _validate_sync_args(mode, name)
    repository = WikiRepository(repo_root.resolve())
    _validate_layout(repository)
    selected = _validate_selected_change(repository, validated_mode, name)
    active_pages = _collect_active_pages(repository)
    archive_pages = _collect_archive_pages(repository)
    warnings = _validate_archive_specs(
        repository, archive_pages, allow_unsynced=allow_unsynced
    )
    _validate_source_artifacts(active_pages, archive_pages)
    _write_outputs(repository, active_pages, archive_pages)
    _validate_outputs(repository, active_pages, archive_pages)
    return SyncResult(
        active_count=len(active_pages),
        archive_count=len(archive_pages),
        include_count=sum(
            len(_expected_includes(page)) for page in [*active_pages, *archive_pages]
        ),
        selected=selected,
        warnings=tuple(warnings),
    )


def verify_wiki(repo_root: Path) -> None:
    """验证已有 WIKI 输出与当前 OpenSpec 状态一致。

    期望值只从 OpenSpec 源构造，不把受检 WIKI 生成字段当作 oracle。
    """

    repository = WikiRepository(repo_root.resolve())
    _validate_layout(repository)
    active_pages = _collect_active_pages(repository)
    archive_pages = _collect_archive_pages(repository)
    _validate_outputs(repository, active_pages, archive_pages)


def _validate_sync_args(mode: str, name: str | None) -> Mode:
    if mode not in {"active", "archive", "all"}:
        raise WikiSyncError(f"不支持的 mode：{mode!r}")
    if mode == "all":
        if name is not None:
            raise WikiSyncError("all 模式不能指定 Change 名称")
        return "all"
    if name is None or not str(name).strip():
        raise WikiSyncError(f"{mode} 模式需要 Change 名称")
    _validate_change_name(name)
    return mode  # type: ignore[return-value]


def _validate_change_name(name: str) -> None:
    stripped = name.strip()
    if not stripped or stripped in {".", ".."}:
        raise WikiSyncError(f"非法 Change 名称：{name!r}")
    if "/" in name or "\\" in name:
        raise WikiSyncError(f"Change 名称不能包含路径分隔符：{name!r}")


def _validate_layout(repository: WikiRepository) -> None:
    if not repository.changes.is_dir():
        raise WikiSyncError("openspec/changes 不存在")
    if not repository.docs.is_dir():
        raise WikiSyncError("docs 不存在")


def _validate_selected_change(
    repository: WikiRepository, mode: Mode, name: str | None
) -> str | None:
    if mode == "all":
        return None
    if not name:
        raise WikiSyncError(f"{mode} 模式需要 Change 名称")
    if mode == "active":
        source = repository.changes / name
        if not source.is_dir() or source.name == "archive":
            raise WikiSyncError(f"active Change 不存在：{name}")
        return source.name
    return _resolve_archive_name(repository, name)


def _resolve_archive_name(repository: WikiRepository, name: str) -> str:
    archive_root = repository.changes / "archive"
    if not archive_root.is_dir():
        raise WikiSyncError("openspec/changes/archive 不存在")
    exact = archive_root / name
    if exact.is_dir():
        return exact.name
    matches = [
        path.name
        for path in archive_root.iterdir()
        if path.is_dir() and path.name.endswith(f"-{name}")
    ]
    if len(matches) != 1:
        detail = "无匹配" if not matches else "、".join(sorted(matches))
        raise WikiSyncError(f"归档名称 {name!r} 匹配结果：{detail}")
    return matches[0]


def _collect_active_pages(repository: WikiRepository) -> list[ChangePage]:
    pages: list[ChangePage] = []
    for source in sorted(repository.changes.iterdir(), key=lambda path: path.name):
        if not source.is_dir() or source.name == "archive":
            continue
        pages.append(
            ChangePage(
                directory_name=source.name,
                title=source.name,
                status="active",
                created_date=_created_date(source),
                archived_date=None,
                source_dir=source,
                output_dir=repository.active_docs / source.name,
            )
        )
    return pages


def _collect_archive_pages(repository: WikiRepository) -> list[ChangePage]:
    archive_root = repository.changes / "archive"
    if not archive_root.is_dir():
        return []
    pages: list[ChangePage] = []
    for source in sorted(archive_root.iterdir(), key=lambda path: path.name, reverse=True):
        if not source.is_dir():
            continue
        archived_date, title = _split_archive_name(source.name)
        created = _metadata_value(source / ".openspec.yaml", "created") or archived_date
        pages.append(
            ChangePage(
                directory_name=source.name,
                title=title,
                status="archived",
                created_date=created,
                archived_date=archived_date,
                source_dir=source,
                output_dir=repository.archive_docs / source.name,
            )
        )
    return pages


def _split_archive_name(name: str) -> tuple[str, str]:
    match = re.fullmatch(r"(\d{4}-\d{2}-\d{2})-(.+)", name)
    if not match:
        raise WikiSyncError(f"归档目录缺少日期前缀：{name}")
    return match.group(1), match.group(2)


def _created_date(change_dir: Path) -> str:
    created = _metadata_value(change_dir / ".openspec.yaml", "created")
    if not created:
        raise WikiSyncError(f"{change_dir}: .openspec.yaml 缺少 created")
    return created


def _metadata_value(path: Path, key: str) -> str | None:
    if not path.is_file():
        return None
    match = re.search(
        rf"^\s*{re.escape(key)}\s*:\s*([^#\n]+?)\s*$",
        path.read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    return match.group(1).strip().strip("\"'") if match else None


def _metadata_bool(path: Path, key: str) -> bool:
    value = _metadata_value(path, key)
    return value is not None and value.lower() in {"true", "yes", "1"}


def _validate_archive_specs(
    repository: WikiRepository,
    pages: list[ChangePage],
    *,
    allow_unsynced: bool,
) -> list[str]:
    errors: list[str] = []
    operations: list[SpecOperation] = []
    for page in reversed(pages):
        specs = sorted((page.source_dir / "specs").glob("*/spec.md"))
        skip_specs = _metadata_bool(page.source_dir / ".openspec.yaml", "skip_specs")
        if not specs:
            if not skip_specs:
                errors.append(f"{page.directory_name}: 缺少 delta specs 且未声明 skip_specs")
            continue
        for spec in specs:
            operations.extend(
                _parse_spec_operations(page.directory_name, spec.parent.name, spec)
            )

    latest: dict[tuple[str, str], SpecOperation] = {}
    for operation in operations:
        latest[(operation.capability, operation.requirement)] = operation

    main_cache: dict[str, dict[str, str]] = {}
    for (capability, requirement), operation in latest.items():
        if capability not in main_cache:
            main_cache[capability] = _requirement_blocks(
                repository.main_specs / capability / "spec.md"
            )
        actual = main_cache[capability].get(requirement)
        if operation.operation in {"ADDED", "MODIFIED"}:
            if actual is None:
                errors.append(
                    f"{operation.archive_name}: {capability} 未同步 requirement {requirement!r}"
                )
            elif operation.body is not None and actual != operation.body:
                errors.append(
                    f"{operation.archive_name}: {capability} requirement {requirement!r} 内容未同步"
                )
        elif actual is not None:
            errors.append(
                f"{operation.archive_name}: {capability} 已移除 requirement {requirement!r} 仍存在"
            )

    if errors and not allow_unsynced:
        preview = "\n  - ".join(errors[:20])
        suffix = f"\n  ... 另有 {len(errors) - 20} 项" if len(errors) > 20 else ""
        raise WikiSyncError(f"归档 delta spec 校验失败：\n  - {preview}{suffix}")
    return errors


def _parse_spec_operations(
    archive_name: str, capability: str, path: Path
) -> list[SpecOperation]:
    text = path.read_text(encoding="utf-8")
    headings = list(OPERATION_RE.finditer(text))
    if not headings:
        raise WikiSyncError(
            f"{archive_name}: {capability} delta spec 缺少可识别 operation"
        )
    operations: list[SpecOperation] = []
    for index, heading in enumerate(headings):
        operation = heading.group(1)
        end = headings[index + 1].start() if index + 1 < len(headings) else len(text)
        section = text[heading.end() : end]
        if operation == "RENAMED":
            rename_re = re.compile(
                r"FROM:\s*`?### Requirement:\s*(.+?)`?\s*\n"
                r"-?\s*TO:\s*`?### Requirement:\s*(.+?)`?\s*(?:\n|$)"
            )
            pairs = rename_re.findall(section)
            if not pairs:
                raise WikiSyncError(
                    f"{archive_name}: {capability} RENAMED 段落无法解析成对 FROM/TO"
                )
            for source, target in pairs:
                operations.append(
                    SpecOperation(
                        archive_name,
                        capability,
                        "REMOVED",
                        _normalize_requirement_name(source),
                        None,
                    )
                )
                operations.append(
                    SpecOperation(
                        archive_name,
                        capability,
                        "ADDED",
                        _normalize_requirement_name(target),
                        None,
                    )
                )
            continue
        blocks = _requirement_blocks_from_text(section)
        if not blocks:
            raise WikiSyncError(
                f"{archive_name}: {capability} {operation} 段落没有 requirement"
            )
        for requirement, body in blocks.items():
            operations.append(
                SpecOperation(
                    archive_name,
                    capability,
                    operation,  # type: ignore[arg-type]
                    requirement,
                    body,
                )
            )
    return operations


def _requirement_blocks(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    return _requirement_blocks_from_text(path.read_text(encoding="utf-8"))


def _requirement_blocks_from_text(text: str) -> dict[str, str]:
    matches = list(REQUIREMENT_RE.finditer(text))
    blocks: dict[str, str] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        body = text[match.end() : end]
        next_section = re.search(r"^##\s+", body, re.MULTILINE)
        if next_section:
            body = body[: next_section.start()]
        blocks[_normalize_requirement_name(match.group(1))] = _normalize_body(body)
    return blocks


def _normalize_requirement_name(requirement: str) -> str:
    normalized = requirement.strip().strip("`").strip()
    normalized = re.sub(r"^###\s*(?:Requirement|需求)\s*[:：]\s*", "", normalized)
    return normalized.strip()


def _normalize_body(body: str) -> str:
    return re.sub(r"\s+", " ", body).strip()


def _validate_source_artifacts(
    active_pages: list[ChangePage], archive_pages: list[ChangePage]
) -> None:
    for page in archive_pages:
        for _, filename in ARTIFACT_SECTIONS:
            path = page.source_dir / filename
            if not path.is_file():
                raise WikiSyncError(f"{page.directory_name}: 缺少必要 artifact {filename}")
    for page in [*active_pages, *archive_pages]:
        for include in _expected_includes(page):
            target = (page.output_dir / include).resolve()
            if not target.is_file():
                raise WikiSyncError(f"{page.directory_name}: include 目标不存在：{include}")


def _collect_page_artifacts(
    page: ChangePage,
) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    source_prefix = Path(os.path.relpath(page.source_dir, page.output_dir)).as_posix()
    artifacts = [
        (title, f"{source_prefix}/{filename}")
        for title, filename in ARTIFACT_SECTIONS
        if (page.source_dir / filename).is_file()
    ]
    specs = [
        (spec.parent.name, f"{source_prefix}/specs/{spec.parent.name}/spec.md")
        for spec in sorted((page.source_dir / "specs").glob("*/spec.md"))
    ]
    return artifacts, specs


def _expected_includes(page: ChangePage) -> list[str]:
    artifacts, specs = _collect_page_artifacts(page)
    return [include for _, include in [*artifacts, *specs]]


def _write_outputs(
    repository: WikiRepository,
    active_pages: list[ChangePage],
    archive_pages: list[ChangePage],
) -> None:
    repository.active_docs.mkdir(parents=True, exist_ok=True)
    repository.archive_docs.mkdir(parents=True, exist_ok=True)
    _remove_stale_directories(
        repository.active_docs, {page.directory_name for page in active_pages}
    )
    _remove_stale_directories(
        repository.archive_docs, {page.directory_name for page in archive_pages}
    )
    for page in [*active_pages, *archive_pages]:
        page.output_dir.mkdir(parents=True, exist_ok=True)
        (page.output_dir / "index.md").write_text(_render_page(page), encoding="utf-8")
    repository.index.write_text(
        _render_index(active_pages, archive_pages), encoding="utf-8"
    )
    repository.config.parent.mkdir(parents=True, exist_ok=True)
    repository.config.write_text(
        _render_config(active_pages, archive_pages), encoding="utf-8"
    )


def _remove_stale_directories(root: Path, expected: set[str]) -> None:
    for path in root.iterdir():
        if not path.is_dir() or path.name in expected:
            continue
        index = path / "index.md"
        if not index.is_file() or GENERATED_MARKER not in index.read_text(encoding="utf-8"):
            raise WikiSyncError(f"拒绝删除非受管 WIKI 目录：{path}")
        shutil.rmtree(path)


def _render_page(page: ChangePage) -> str:
    lines = [
        "---",
        f"title: {page.title}",
        f"status: {page.status}",
        f"createdDate: {page.created_date}",
    ]
    if page.archived_date:
        lines.append(f"archivedDate: {page.archived_date}")
    lines.extend(["---", "", GENERATED_MARKER, "", f"# {page.title}", ""])
    lines.extend(
        [f"> 状态：{'进行中' if page.status == 'active' else '已归档'}", ""]
    )

    artifacts, specs = _collect_page_artifacts(page)
    for title, include in artifacts:
        lines.extend([f"## {title}", "", f"<!--@include: {include}-->", ""])
    if specs:
        lines.extend(["## 规格变更", ""])
        for capability, include in specs:
            lines.extend(
                [f"### {capability}", "", f"<!--@include: {include}-->", ""]
            )
    if not artifacts and not specs:
        lines.extend(["当前 Change 尚无可展示 artifact。", ""])
    return "\n".join(lines).rstrip() + "\n"


def _render_index(active_pages: list[ChangePage], archive_pages: list[ChangePage]) -> str:
    lines = [
        "---",
        "title: OpenSpec 变更",
        "---",
        "",
        GENERATED_MARKER,
        "",
        "# OpenSpec 变更",
        "",
        "## 进行中",
        "",
    ]
    lines.extend(_render_link_list(active_pages, empty="当前没有进行中的变更。"))
    lines.extend(["", "## 已归档", ""])
    lines.extend(_render_link_list(archive_pages, empty="当前没有已归档的变更。"))
    return "\n".join(lines) + "\n"


def _render_link_list(pages: list[ChangePage], *, empty: str) -> list[str]:
    if not pages:
        return [empty]
    return [f"- [{page.title}]({page.link})" for page in pages]


def _render_config(active_pages: list[ChangePage], archive_pages: list[ChangePage]) -> str:
    active_items = _render_sidebar_items(active_pages)
    archive_items = _render_sidebar_items(archive_pages)
    template = '''// Generated by scripts/sync_wiki.py; do not edit.
import { defineConfig } from "vitepress";

const activeItems = [
__ACTIVE_ITEMS__
];

const archivedItems = [
__ARCHIVE_ITEMS__
];

export default defineConfig({
  lang: "zh-CN",
  title: "On-call Pilot WIKI",
  description: "On-call Pilot 项目文档与 OpenSpec 变更记录",
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: "首页", link: "/" },
      { text: "变更 WIKI", link: "/changes/" }
    ],
    sidebar: {
      "/changes/": [
        { text: "总览", items: [{ text: "变更索引", link: "/changes/" }] },
        { text: "进行中", collapsed: false, items: activeItems },
        { text: "已归档", collapsed: true, items: archivedItems }
      ]
    },
    search: { provider: "local" },
    outline: { level: [2, 3], label: "本页目录" },
    docFooter: { prev: "上一页", next: "下一页" },
    sidebarMenuLabel: "目录",
    returnToTopLabel: "返回顶部"
  }
});
'''
    return template.replace("__ACTIVE_ITEMS__", active_items).replace(
        "__ARCHIVE_ITEMS__", archive_items
    )


def _render_sidebar_items(pages: list[ChangePage]) -> str:
    return "\n".join(
        f"  {{ text: {json.dumps(page.title, ensure_ascii=False)}, link: {json.dumps(page.link)} }},"
        for page in pages
    )


def _validate_outputs(
    repository: WikiRepository,
    active_pages: list[ChangePage],
    archive_pages: list[ChangePage],
) -> None:
    if not repository.active_docs.is_dir() or not repository.archive_docs.is_dir():
        raise WikiSyncError("WIKI 输出目录不完整")
    if not repository.index.is_file() or not repository.config.is_file():
        raise WikiSyncError("WIKI 索引或 VitePress 配置缺失")

    expected_active = {page.directory_name for page in active_pages}
    expected_archive = {page.directory_name for page in archive_pages}
    actual_active = {path.name for path in repository.active_docs.iterdir() if path.is_dir()}
    actual_archive = {path.name for path in repository.archive_docs.iterdir() if path.is_dir()}
    if actual_active != expected_active or actual_archive != expected_archive:
        raise WikiSyncError("WIKI 页面目录与 OpenSpec Change 目录不一致")

    for page in [*active_pages, *archive_pages]:
        _validate_page(page)

    expected_index = _render_index(active_pages, archive_pages)
    actual_index = repository.index.read_text(encoding="utf-8")
    if actual_index != expected_index:
        raise WikiSyncError("docs/changes/index.md 与 OpenSpec 期望全文不一致")

    expected_config = _render_config(active_pages, archive_pages)
    actual_config = repository.config.read_text(encoding="utf-8")
    if actual_config != expected_config:
        raise WikiSyncError("docs/.vitepress/config.mts 与 OpenSpec 期望全文不一致")

    expected_links = [page.link for page in [*active_pages, *archive_pages]]
    index_links = [
        match.group(1)
        for line in actual_index.splitlines()
        if (match := INDEX_LINK_RE.match(line))
    ]
    config_links = CONFIG_LINK_RE.findall(actual_config)
    if index_links != expected_links or config_links != expected_links:
        raise WikiSyncError("docs/changes/index.md 与 VitePress 导航顺序不一致")


def _validate_page(page: ChangePage) -> None:
    output = page.output_dir / "index.md"
    if not output.is_file():
        raise WikiSyncError(f"WIKI 页面不存在：{output}")
    text = output.read_text(encoding="utf-8")
    includes = INCLUDE_RE.findall(text)
    for include in includes:
        target = (output.parent / include).resolve()
        if not target.is_file():
            raise WikiSyncError(f"{output}: include 目标不存在：{include}")
    expected_text = _render_page(page)
    if text != expected_text:
        raise WikiSyncError(f"{output}: 页面全文与 OpenSpec 期望不一致")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("active", "archive", "all"))
    parser.add_argument("name", nargs="?")
    parser.add_argument(
        "--allow-unsynced",
        action="store_true",
        help="仅在用户明确批准后跳过真正未同步的归档 delta specs",
    )
    args = parser.parse_args()
    if args.mode != "all" and not args.name:
        parser.error("active 和 archive 模式需要 Change 名称")
    return args


def main() -> int:
    args = _parse_args()
    repository_root = Path(__file__).resolve().parents[1]
    try:
        result = sync_wiki(
            repository_root,
            args.mode,
            args.name,
            allow_unsynced=args.allow_unsynced,
        )
    except WikiSyncError as error:
        print(f"wiki-sync 失败：{error}", file=sys.stderr)
        return 1

    for warning in result.warnings:
        print(f"警告：已按明确授权跳过：{warning}")
    print(
        "wiki-sync 完成："
        f"{result.active_count} 个 active，{result.archive_count} 个 archived，"
        f"已验证 {result.include_count} 个 include"
    )
    if result.selected:
        print(f"选中 Change：{result.selected}")
    print("导航验证通过：docs/changes/index.md 与 docs/.vitepress/config.mts 一致")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
